spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to White Bank accounts related prod APIs "
  contactDetails:
    name: "Arthur Peck - Product Owner"
    email: "arthura@whitebank.com"
  onCallSupport:
    - (895) 392-4829
    - (895) 203-0384