spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to White Bank accounts related QA APIs "
  contactDetails:
    name: "Helen Petrovsky - QA Lead"
    email: "helen@mail.com"
  onCallSupport:
    - (812) 555-6785
    - (812) 565-9865